#!/bin/bash
# qvm-backup-to-appvm
# Version: 0.1
# Copy files from dom0 to an archive in an AppVM
# Usage  : qvm-backup-to-appvm <Source> <AppVM> <Destination> <Archive>
# Example: qvm-backup-to-appvm ~/bin my-untrusted /home/user/backup backup.tgz

Source=$1
AppVM=$2
Destination=$3
Archive=`date +%Y.%m.%d-%H.%M`_$4

tar -cvzf /tmp/$Archive $Source
qvm-move-to-vm $AppVM /tmp/$Archive
echo "mv ~/QubesIncoming/dom0/$Archive $Destination && \
      rm ~/QubesIncoming/dom0/qvm-backup_helperscript.sh" >> /tmp/qvm-backup_helperscript.sh
chmod +x /tmp/qvm-backup_helperscript.sh
qvm-move-to-vm $AppVM /tmp/qvm-backup_helperscript.sh
qvm-run $AppVM /home/user/QubesIncoming/dom0/qvm-backup_helperscript.sh
